version: '3'

services:
  hxscan-tool:
    image: snow7/hxscan:tool
    container_name: hxscan-tool
    ports:
      - "3443:3443"
    cap_add:
      - LINUX_IMMUTABLE
    networks:
      - hxscan-network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:3443"]
      interval: 10s
      timeout: 5s
      retries: 5

  hxscan-app:
    image: snow7/hxscan:app
    container_name: hxscan-app
    ports:
      - "8000:8000"
    environment:
      - API_URL=https://hxscan-tool:3443
    depends_on:
      hxscan-tool:
        condition: service_healthy
    networks:
      - hxscan-network

networks:
  hxscan-network:
    name: hxscan-network