version: '3'

services:
  hxscan-tool-beta:
    image: sakura501/hxscan-tool:v1
    container_name: hxscan-tool-beta
    networks:
      - hxscan-network
    restart: unless-stopped

  hxscan-app-beta:
    image: snow7/hxscan-app:v1.3
    container_name: hxscan-app-beta
    ports:
      - "8000:8000"
    environment:
      - API_URL=https://hxscan-tool-beta:3443
    depends_on:
      - hxscan-tool-beta
    networks:
      - hxscan-network
    restart: unless-stopped
    volumes:
      - /d/test/dirscan_results:/app/dirscan_results
      - /d/test/info_leak_results:/app/info_leak_results
      - /d/test/port_scan_results:/app/port_scan_results
      - /d/test/finger_print_results:/app/finger_print_results
      - /d/test/media:/app/media
      - /d/test/database:/app/database # 持久化数据库

networks:
  hxscan-network:
    name: hxscan-network