# Generated by Django 3.1.4 on 2024-10-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryscan',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
