# Generated by Django 3.1.4 on 2024-10-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscan_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portscan',
            name='result',
        ),
        migrations.AddField(
            model_name='portscan',
            name='result_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portscan',
            name='status',
            field=models.CharField(choices=[('process', 'Processing'), ('finish', 'Finished')], max_length=10),
        ),
    ]
