# Generated by Django 3.1.4 on 2024-10-23 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webscan_backend', '0003_infoleak'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('result_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('process', 'Processing'), ('finish', 'Finished')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
