# Generated by Django 3.1.4 on 2024-10-11 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webscan', '0003_auto_20210228_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='操作')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('content_type', models.CharField(max_length=100, verbose_name='内容类型')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('object_repr', models.CharField(max_length=200, verbose_name='对象描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-action_time'],
            },
        ),
    ]
