# Generated by Django 3.1.4 on 2024-10-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0005_auto_20241011_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='log',
            name='object_repr',
        ),
    ]
