# Generated by Django 3.1.4 on 2024-10-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0006_auto_20241011_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_name', models.CharField(max_length=200, verbose_name='漏洞名称')),
                ('vuln_details', models.CharField(blank=True, default='未知', max_length=200, verbose_name='漏洞描述')),
                ('vuln_type', models.CharField(blank=True, default='未知', max_length=200, verbose_name='漏洞分类')),
            ],
            options={
                'verbose_name': '漏洞列表',
                'verbose_name_plural': '漏洞列表',
            },
        ),
    ]
