# Generated by Django 3.1.4 on 2021-02-28 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0006_auto_20241011_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_name', models.TextField(max_length=200, verbose_name='漏洞名称')),
                ('vuln_details', models.TextField(blank=True, default='未知', max_length=200, verbose_name='漏洞详情')),
                ('vuln_type', models.TextField(blank=True, default='未知', max_length=200, verbose_name='漏洞类型')),
            ],
            options={
                'verbose_name': '漏洞列表',
                'verbose_name_plural': '漏洞列表',
                'ordering': ['-id'],
            },
        ),
    ]
